<a href="https://colab.research.google.com/github/dhanasekarenb/Machine_learning/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is powerful because it offloads heavy numerical work to compiled C code.
Key reasons:

Vectorization: operations act on whole arrays rather than looping in Python.

C-backend: most array ops are C functions → near-native speed.

Contiguous memory: arrays store values in one continuous memory block, which the CPU cache loves.

In [ ]:
import numpy as np
import time

x = np.random.rand(10_000_000)
start = time.time()
y = x * 2        # vectorized
print("Vectorized:", time.time() - start)

start = time.time()
y = [i * 2 for i in x]   # Python loop
print("Loop:", time.time() - start)

Vectorized: 0.029839038848876953
Loop: 2.491884708404541


Broadcasting lets arrays of different shapes interact without copying data.
Rule summary:

Compare shapes from right → left.

Dimensions must either be equal or one = 1. for ex : (4, 1) (1, 4)

NumPy stretches (but doesn’t duplicate) the 1-sized dimension.

https://youtu.be/P67wiuTx7l0?si=0jZU7jcoHf7XFlox

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
#[[10,10,10], [10,10,10]] scalar converts like this when we try to add
result = array_2d + scalar
print(result)

[[11 12 13]
 [14 15 16]]


Advanced Indexing

In [ ]:
# Boolean masking

arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print(mask)
print(arr[mask])   # [4 5]

# Integer indexing
data = np.arange(10, 20)
idx = [0, 3, 7]
print(data[idx])   # specific positions

# Combined
arr[arr % 2 == 0] = 0   # set even numbers to zero
print(arr)

[False False False  True  True]
[4 5]
[10 13 17]
[1 0 3 0 5]


Mean Square Error (MSE)

In [ ]:
import numpy as np

y_act = np.array([1, 2, 3])
y_pred = np.array([1.1, 1.9, 3.2])

MSE = np.mean((y_act - y_pred) **2)
print(MSE)


0.020000000000000035


Gradient of MSE for Linear Regression

In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([3, 5, 7, 9])

w, b = 1.0, 0.0

y_pred = (w*x + b)
print(y_pred)

error = y - y_pred

mse = np.mean(error**2)
print(mse)

n = len(x)

db = -2/n * (np.sum(error))
dw = -2/n * (np.sum((error) * (x)))

print(db, dw)




[1. 2. 3. 4.]
13.5
-7.0 -20.0
